version: '3.6'

services:
  bitcoin:
    restart: always
    image: realnuts/docker_bitcoind:v1.19.1.2
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/btc_data:/bitcoin/data
    command:
#      - "-printtoconsole"
       - "-regtest=0"
       - "-rest"
       - "-rpcallowip=0/32"
       - "-rpcpassword=test"
       - "-wallet=wallet1"
       - "-rpcport=8333"
       - "-rpcuser=foo"
       - "-server"
