version: '3.6'

services:
  bitcoin:
    restart: on-failure
    image: realnuts/docker_bitcoind:v1.20.0.0
    ports:
      - "8332:8332"
      - "8333:8333"
      - "18332:18332"
      - "18333:18333"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/btc_data:/bitcoin/data
    command:
       - "-printtoconsole"
       - "-regtest=0"
       - "-rest"
       - "-rpcallowip=172.0.0.0/8"
       - "-rpcallowip=172.16.36.0/24"
       - "-rpcallowip=127.0.0.1/0"
       - "-rpcuser=foo"
       - "-rpcpassword=test"
       - "-wallet=wallet1"
       - "-txindex"
       - "-rpcport=8333"
       - "-rpcbind=0.0.0.0:8332"
       - "-server"
